packages:
  - 'packages/examples'
  - 'packages/siesta/packages/siesta'
  - 'packages/siesta/packages/chained-iterator'
  - 'packages/siesta/packages/typescript-mixin-class'
  - 'packages/siesta/packages/typescript-serializable-mixin'
  - 'packages/siesta/packages/chronograph'
onlyBuiltDependencies:
  - "typescript"
  - "typedoc"
  - "esm"
